---
title: "reading_COVID_nursing_home20201022"
author: "Harold Pollack"
date: "10/23/2020"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo=FALSE}

packs <- c('formattable'
           ,'survey'
           ,'questionr'
           , 'dplyr'
           ,'descr'
           ,'data.table'
           ,'RSocrata')



if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packs)

knitr::opts_chunk$set(echo = TRUE)
```

Program that reads CMS nursing home data and performs weighted tables

```{r read admissions dataset}

#grab data using RSocrata
#will need an api token define it here, get one at https://dev.socrata.com/docs/app-tokens.html or https://support.socrata.com/hc/en-us/articles/210138558-Generating-an-App-Token

#if you create a global variable .Renviron in your home directory to take you to the directory you want to work in you can use the following lines of code to use that and be in the right directory to access local files

if(file.exists(Sys.getenv('NURSING_HOME_WD'))){
  mywd <- Sys.getenv('NURSING_HOME_WD')
  print(file.exists(Sys.getenv('NURSING_HOME_WD')))
}

#this relies on your dataset having this name
if(exists('mywd')){
  mydata <- read.csv(paste(mywd,"COVID-19_Nursing_Home_Dataset20201023.csv",sep=''))
}else{
  
  #put in your path to file if you want to use local file and did not set up .Renviron
  if(file.exists("/Users/haroldpollack/Downloads/COVID-19_Nursing_Home_Dataset20201023.csv")){
    
    mydata <- read.csv("/Users/haroldpollack/Downloads/COVID-19_Nursing_Home_Dataset20201023.csv")

  }else{

    #you can put your token in an .Renviron file that can be put in your home directory
    #if you name the token as done below, then you can use the following command
    
    if(!exists('token')){
      if(file.exists(Sys.getenv('SOCRATA_TOKEN'))){
      mywd <- Sys.getenv('SOCRATA_TOKEN')
      print(file.exists(Sys.getenv('SOCRATA_TOKEN')))
      }
      else{
      token <- NA}
    }
    
    endpoint <- 'https://data.cms.gov/resource/s2uc-8wxp.json'
    url <- 'https://data.cms.gov/resource/s2uc-8wxp.json?$limit=50000&$offset=0'
    start_row<- 0
    mydata <- read.socrata(url)
    new_df_len <- nrow(df)
    
    if(!is.na(token)){
    # '''
    # Fill in with code for people with tokens if they can get them?
    # '''
    }else{
      while(new_df_len > 1)
      start_row <- start_row +50000
      url <- paste0(endpoint,'$limit=50000','&$offset=',start_row,'&$order=Week Ending')
      new_df <- read.socrata(url)
      new_df_len <- nrow(new_df)
      mydata <- rbind(df, mydata)
    }
  }
}

#str(mydata)
table(mydata$Week.Ending)
aggregate(mydata$Staff.Weekly.COVID.19.Deaths, by=list(Category=mydata$Week.Ending), na.rm=TRUE, FUN=sum)
aggregate(mydata$Residents.Weekly.COVID.19.Deaths, by=list(Category=mydata$Week.Ending), na.rm=TRUE, FUN=sum)
#
#   Indicate latest week
#
max(mydata$Week.Ending)
#
# from https://data.cms.gov/api/views/s2uc-8wxp/rows.csv?accessType=DOWNLOAD, https://data.cms.gov/Special-Programs-Initiatives-COVID-19-Nursing-Home/COVID-19-Nursing-Home-Dataset/s2uc-8wxp/data
#
#summary(mydata)
#head(mydata)
myvars <- c("Residents.Weekly.COVID.19.Deaths","Federal.Provider.Number","Staff.Weekly.COVID.19.Deaths")
newdata <- mydata[myvars]
newdata<-arrange(newdata,Federal.Provider.Number)
v_sums <-newdata %>%
    summarize_if(is.numeric, sum, na.rm=TRUE)
#summary(v_sums)
resident_deaths<- v_sums$Residents.Weekly.COVID.19.Deaths
staff_deaths<-v_sums$Staff.Weekly.COVID.19.Deaths
resident_deaths
staff_deaths

wtd.table(mydata$Provider.State, mydata$One.Week.Supply.of.N95.Masks, weights=mydata$Total.Number.of.Occupied.Beds)
#ct<- crosstab(mydata$Provider.State, mydata$One.Week.Supply.of.N95.Masks, weight=mydata$Total.Number.of.Occupied.Beds, xlab = "state", ylab = "Mask supply")
#ct
maxweek<-max(mydata$Week.Ending)
mydata_last<- mydata  %>% filter(Week.Ending == maxweek)
#mydata_last<-mydata[,mydata$Week.Ending<-maxweek]
wtd.table(mydata_last$Provider.State, mydata_last$One.Week.Supply.of.N95.Masks, weights=mydata_last$Total.Number.of.Occupied.Beds)
wtd.table(mydata_last$Provider.State, mydata_last$One.Week.Supply.of.Gowns, weights=mydata_last$Total.Number.of.Occupied.Beds)
wtd.table(mydata_last$Provider.State, mydata_last$Shortage.of.Nursing.Staff, weights=mydata_last$Total.Number.of.Occupied.Beds)
wtd.table(mydata_last$Provider.State, mydata_last$Shortage.of.Clinical.Staff, weights=mydata_last$Total.Number.of.Occupied.Beds)
wtd.table(mydata_last$Provider.State, mydata_last$Shortage.of.Aides, weights=mydata_last$Total.Number.of.Occupied.Beds)
custom_glimpse <- function(df) {
  data.frame(
    col_name = colnames(df),
    col_index = 1:ncol(df),
    col_class = sapply(df, class),
    row.names = NULL
  )
}
custom_glimpse(mydata)
```

quick glimse at the downloaded variables.

```{r quickly glimpsing the variables}
#
#    function from https://stackoverflow.com/questions/56466715/explore-data-frame-and-provide-numbered-list-of-variables-in-r
#

custom_glimpse <- function(df) {
  data.frame(
    col_name = colnames(df),
    col_index = 1:ncol(df),
    col_class = sapply(df, class),
    row.names = NULL
  )
}
#custom_glimpse(mydata)
```
